// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPATkHYR19IMhMJFZ42Vn-pWf7Jznsk9s',
    appId: '1:617388041925:web:19a1ef473cacce743d32ac',
    messagingSenderId: '617388041925',
    projectId: 'zola-firebase',
    authDomain: 'zola-firebase.firebaseapp.com',
    storageBucket: 'zola-firebase.appspot.com',
    measurementId: 'G-1SRJF4HM6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbUNWJaCiJTXkcYWDrh-JexWovyCIrm4s',
    appId: '1:617388041925:android:670497d5838425023d32ac',
    messagingSenderId: '617388041925',
    projectId: 'zola-firebase',
    storageBucket: 'zola-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGxpG7PzZyjCCo3KPYgtVKOt6v19gZ3SA',
    appId: '1:617388041925:ios:eeb61a2f6375b0823d32ac',
    messagingSenderId: '617388041925',
    projectId: 'zola-firebase',
    storageBucket: 'zola-firebase.appspot.com',
    iosClientId: '617388041925-ge3iaf63hint7t5871mn8ee90qfpgfsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.zola',
  );
}
